//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace jeza.ioFTPD.Manager.Client
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jeza.ioFTPD.Manager", ConfigurationName="IManager")]
    public interface IManager
    {
    
        [System.ServiceModel.OperationContractAttribute(Action="http://jeza.ioFTPD.Manager/IManager/ProcessZipScript", ReplyAction="http://jeza.ioFTPD.Manager/IManager/ProcessZipScriptResponse")]
        int ProcessZipScript(string[] args);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://jeza.ioFTPD.Manager/IManager/ProcessArchiveScript", ReplyAction="http://jeza.ioFTPD.Manager/IManager/ProcessArchiveScriptResponse")]
        int ProcessArchiveScript(string[] args);
    
        [System.ServiceModel.OperationContractAttribute(Action="http://jeza.ioFTPD.Manager/IManager/ProcessManager", ReplyAction="http://jeza.ioFTPD.Manager/IManager/ProcessManagerResponse")]
        int ProcessManager(string[] args);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagerChannel : IManager, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class ManagerClient : System.ServiceModel.ClientBase<IManager>, IManager
    {
    
        public ManagerClient()
        {
        }
    
        public ManagerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
        {
        }
    
        public ManagerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public ManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
        {
        }
    
        public ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
        {
        }
    
        public int ProcessZipScript(string[] args)
        {
            return Channel.ProcessZipScript(args);
        }
    
        public int ProcessArchiveScript(string[] args)
        {
            return Channel.ProcessArchiveScript(args);
        }
    
        public int ProcessManager(string[] args)
        {
            return Channel.ProcessManager(args);
        }
    }
}