//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker.Web {
    
    
    public partial class ManageItems {
        
        /// <summary>
        /// formManageItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm formManageItems;
        
        /// <summary>
        /// panelManageItemsHead control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelManageItemsHead;
        
        /// <summary>
        /// hyperLinkManageItemsHeadMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hyperLinkManageItemsHeadMain;
        
        /// <summary>
        /// panelManageItemsBodyItemTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelManageItemsBodyItemTypes;
        
        /// <summary>
        /// labelManageItemsBodyItemTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemTypes;
        
        /// <summary>
        /// textBoxManageItemsBodyItemTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageItemsBodyItemTypes;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemTypesSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemTypesSubmit;
        
        /// <summary>
        /// panelManageItemsBodyItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelManageItemsBodyItems;
        
        /// <summary>
        /// labelManageItemsBodyItemsSelect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemsSelect;
        
        /// <summary>
        /// dropDownListManageItemsBodyItemsSelect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropDownListManageItemsBodyItemsSelect;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemsSelect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemsSelect;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemsAddNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemsAddNew;
        
        /// <summary>
        /// labelManageItemsBodyItemsSubmitItemId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemsSubmitItemId;
        
        /// <summary>
        /// labelManageItemsBodyItemsSubmitItemName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemsSubmitItemName;
        
        /// <summary>
        /// labelManageItemsBodyItemsSubmitItemNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemsSubmitItemNote;
        
        /// <summary>
        /// labelManageItemsBodyItemsSubmitItemType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageItemsBodyItemsSubmitItemType;
        
        /// <summary>
        /// textBoxManageItemsBodyItemsSubmitItemId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageItemsBodyItemsSubmitItemId;
        
        /// <summary>
        /// textBoxManageItemsBodyItemsSubmitItemName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageItemsBodyItemsSubmitItemName;
        
        /// <summary>
        /// textBoxManageItemsBodyItemsSubmitNote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageItemsBodyItemsSubmitNote;
        
        /// <summary>
        /// dropDownListManageItemsBodyItemsSubmitItemType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropDownListManageItemsBodyItemsSubmitItemType;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemsSubmit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemsSubmit;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemsUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemsUpdate;
        
        /// <summary>
        /// linkButtonManageItemsBodyItemsDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageItemsBodyItemsDelete;
    }
}
