DECLARE @sql VARCHAR(MAX)
DECLARE @sql_db VARCHAR(MAX)
DECLARE @Search_Text VARCHAR(MAX) = '%mobitel%'

DECLARE @tbl_COLUMNS TABLE
(
id INT IDENTITY(1,1)
, TABLE_CATALOG VARCHAR(MAX)
, TABLE_SCHEMA VARCHAR(MAX)
, TABLE_NAME VARCHAR(MAX)
, COLUMN_NAME VARCHAR(MAX)
)

DECLARE @tbl_RESULTS TABLE
(
TABLE_CATALOG VARCHAR(MAX)
, TABLE_SCHEMA VARCHAR(MAX)
, TABLE_NAME VARCHAR(MAX)
, COLUMN_NAME VARCHAR(MAX)
)

DECLARE db_cursor CURSOR FOR
SELECT name FROM sys.databases WHERE name NOT IN('Tempdb', 'Master') ORDER BY name
OPEN db_cursor
FETCH NEXT FROM db_cursor INTO @sql_db
WHILE @@FETCH_STATUS = 0
BEGIN
SET @sql = 'SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME FROM [' + @sql_db + '].INFORMATION_SCHEMA.COLUMNS WHERE DATA_TYPE LIKE''' + '%CHAR%' +''' ORDER BY TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME'
INSERT INTO @tbl_COLUMNS (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME)
EXEC(@sql)

FETCH NEXT FROM db_cursor INTO @sql_db
END
CLOSE db_cursor
DEALLOCATE db_cursor

DECLARE @sql_tbl_id INT
DECLARE @db VARCHAR(MAX)
DECLARE @sc VARCHAR(MAX)
DECLARE @tb VARCHAR(MAX)
DECLARE @cl VARCHAR(MAX)

DECLARE column_cursor CURSOR FOR
SELECT id FROM @tbl_COLUMNS ORDER BY id
OPEN column_cursor
FETCH NEXT FROM column_cursor INTO @sql_tbl_id
WHILE @@FETCH_STATUS = 0
BEGIN

SELECT 
@db = TABLE_CATALOG 
, @sc = TABLE_SCHEMA
, @tb = TABLE_NAME
, @cl = COLUMN_NAME
FROM @tbl_COLUMNS
WHERE id = @sql_tbl_id

SET @sql = 'SELECT ''' + @db + ''' AS TABLE_CATALOG, ''' + @sc + ''' AS TABLE_SCHEMA, ''' + @tb + ''' AS TABLE_NAME, ''' + @cl + ''' AS COLUMN_NAME FROM [' + @db + '].[' + @sc + '].[' + @tb + '] WHERE ' + @cl + ' LIKE ''' + @Search_Text + ''''
INSERT INTO @tbl_RESULTS (TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME)
EXEC(@sql)

FETCH NEXT FROM column_cursor INTO @sql_tbl_id
END

CLOSE column_cursor
DEALLOCATE column_cursor

SELECT
TABLE_CATALOG
, TABLE_SCHEMA
, TABLE_NAME
, COLUMN_NAME
, COUNT(*) AS TOTAL_COUNT
FROM @tbl_RESULTS
GROUP BY 
TABLE_CATALOG
, TABLE_SCHEMA
, TABLE_NAME
, COLUMN_NAME