//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductTracker.Web {
    
    
    public partial class ManageShopItems {
        
        /// <summary>
        /// formManageShopItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm formManageShopItems;
        
        /// <summary>
        /// hyperLinkManageShopItemsMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hyperLinkManageShopItemsMain;
        
        /// <summary>
        /// labelManageShopItemsBodyInputItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyInputItems;
        
        /// <summary>
        /// dropDownListManageShopItemsBodyInputItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropDownListManageShopItemsBodyInputItems;
        
        /// <summary>
        /// labelManageShopItemsBodyInputShops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyInputShops;
        
        /// <summary>
        /// dropDownListManageShopItemsBodyInputShops control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dropDownListManageShopItemsBodyInputShops;
        
        /// <summary>
        /// labelManageShopItemsBodyInputPriceGross control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyInputPriceGross;
        
        /// <summary>
        /// textBoxManageShopItemsBodyInputPriceGross control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyInputPriceGross;
        
        /// <summary>
        /// labelManageShopItemsBodyInputPriceNet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyInputPriceNet;
        
        /// <summary>
        /// textBoxManageShopItemsBodyInputPriceNet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyInputPriceNet;
        
        /// <summary>
        /// labelManageShopItemsBodyInputNumberOfItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyInputNumberOfItems;
        
        /// <summary>
        /// textBoxManageShopItemsBodyInputNumberOfItems control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyInputNumberOfItems;
        
        /// <summary>
        /// linkButtonManageShopItemsBodyInputAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageShopItemsBodyInputAdd;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersInputShopItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersInputShopItem;
        
        /// <summary>
        /// textBoxManageShopItemsBodyTrackersInputShopItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyTrackersInputShopItem;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersInputDateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersInputDateTime;
        
        /// <summary>
        /// textBoxManageShopItemsBodyTrackersInputDateTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyTrackersInputDateTime;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersInputSoldCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersInputSoldCount;
        
        /// <summary>
        /// textBoxManageShopItemsBodyTrackersInputSoldCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textBoxManageShopItemsBodyTrackersInputSoldCount;
        
        /// <summary>
        /// linkButtonManageShopItemsBodyTrackersInputAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton linkButtonManageShopItemsBodyTrackersInputAdd;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsTotal;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsTotalNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsTotalNumber;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsSold control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsSold;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsSoldNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsSoldNumber;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsGrossReceived control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsGrossReceived;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsGrossReceivedNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsGrossReceivedNumber;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsNetReceived control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsNetReceived;
        
        /// <summary>
        /// labelManageShopItemsBodyTrackersStatsNetReceivedNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsBodyTrackersStatsNetReceivedNumber;
        
        /// <summary>
        /// gridViewManageShopItemsBodyTrackersList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gridViewManageShopItemsBodyTrackersList;
        
        /// <summary>
        /// gridViewManageShopItemsBodyList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gridViewManageShopItemsBodyList;
        
        /// <summary>
        /// labelManageShopItemsStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labelManageShopItemsStatus;
    }
}
