//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("jeza Item Tracker")]
[assembly: AssemblyDescription("Item Tracker")]
[assembly: AssemblyCompany("JezaSoft")]
[assembly: AssemblyProduct("jeza.Item.Tracker")]
[assembly: AssemblyCopyright("Copyright JezaSoft 2011")]
[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("f22540e0-6773-403c-bc96-769b54770e35")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]


