//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("jeza ioFTPD Tools")]
[assembly: AssemblyDescription("Tools for ioFTPD")]
[assembly: AssemblyCompany("JezaSoft")]
[assembly: AssemblyProduct("jeza.ioFTPD.Tools")]
[assembly: AssemblyCopyright("Copyright JezaSoft 2011")]
[assembly: AssemblyConfiguration("Release")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("d038566a-1937-478a-b5c5-b79c4afb253d")]
[assembly: AssemblyVersion("4.3.0.0")]
[assembly: AssemblyFileVersion("4.3.0.0")]


